# -*- coding: utf-8 -*-
"""Raman_day_8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fuTHn_umX52fU3buPjzSLLDBCzOUOG8K
"""

import pandas as pd
df = pd.read_excel('/content/m.xlsx')

#printing head of dataset
df.head()
#printing tail of the dataset
df.tail()
df.describe()

#maximum attack score
a = df['Attack'].max()
print(a)
max_attack =df.loc[df['Attack']==df['Attack'].max()]
print("The character with the maximum attack score")
print(max_attack)

#minimum attack score
min_attack =df.loc[df['Attack'].min()]
print("The character with the minimum attack score")
print(min_attack)

#maximum defense score
max_defense =df.loc[df['Defense'].max()]
print("The character with the maximum defense score")
print(max_defense)

#minimum defense score
min_defense =df.loc[df['Defense'].min()]
print("The character with the minimum defense score")
print(min_defense)

#getting dataset for legendary characters
df1 = df[df['Legendary']==True]
print("New Dataframe consisting of legendary characters")
print(df1.head(3))

#character's average of speed, defense and attack
df['Average'] = (df['Speed'] + df['Attack'] + df['Defense'])/3
print(df.head(2))
print("Maximum average among characters is = ",df['Average'].max())
print("Minimum average among characters is = ",df['Average'].min())

# getting data for minimum average character
min_avg =df['Average'].min()
print(min_avg)

#creating a new excel file
avg=[1,2,3,4]
new_df = df.append({"Total_avg":avg},ignore_index=True)
new_df.to_excel("m11.xlsx",index=False)
new_df1 = pd.read_excel('m11.xlsx')
print(new_df1.head(2))

#data of second generation characters
df2 = df[df['Generation']==2]
df2.head(3)

#grouping the dataset on basis of name speed and attack
char = df.groupby(['Name','Speed','Attack']).Name.count()
print(char)

# to check the duplicated data points in the dataset
duplicate = df[df.duplicated()]
print(duplicate)

#total number of characters in the dataset
print("Total number of characters in the dataset is = ",df['count'].sum())

#data for characters who can fly
df3 = df[df['Type 2']=="Flying"]
df3.head(2)